config/routes.rb
Rails.application.routes.draw do
  root 'inventory#all_Product'

  get 'product' =>'inventory#one_product'

  get 'category' => 'inventory#category'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  def all_Product
  	@products = Product.all
  end

  def one_product
  	@product = Product.find(params[:id])
  end

  def category
  	@prod_cat = params[:category]
  	@products = Product.where(category: @prod_cat)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/views/inventory/all_Product.html.erb
<h1>All Products</h1>

<table>
	<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>Price</th>
			<th>Category</th>
		</tr>
	</thead>

	<tbody>
		<% @products.each do |product| %>
			<tr>
			<td><%= product.id %></td>
			<td><%= link_to product.name,product_path(id: product.id) %></td>
			<td><%= number_to_currency(product.price) %></td>
			<td><%= link_to product.category, category_path(category: product.category) %></td></tr>
		<% end %>
	</tbody>
</table>

app/views/inventory/category.html.erb
<h1>Inventory: <%= @prod_cat %></h1>

<table>
	<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>Price</th>
			<th>Category</th>
		</tr>
	</thead>

	<tbody>
		<% @products.each do |product| %>
			<tr>
			<td><%= product.id %></td>
			<td><%= product.name %></td>
			<td><%= number_to_currency(product.price) %></td>
			<td><%= product.category %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/inventory/one_product.html.erb
<h1>Product Info: <%= @product.name %></h1>

<table>
	<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>Price</th>
			<th>Category</th>
		</tr>
	</thead>

	<tbody>
			<tr>
			<td><%= @product.id %></td>
			<td><%= @product.name %></td>
			<td><%= number_to_currency(product.price) %></td>
			<td><%= @product.category %></td></tr>
	</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>